name: CI workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  back-end-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and run back-end tests with Maven
        run: mvn -B clean verify

      - name: Get back-end coverage report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: back-end-coverage
          path: back/target/site/jacoco
      
      - name: SonarCloud scan back-end
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: back
          args: -Dsonar.qualitygate.wait=true

  front-end-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci

      - name: Run front-end tests
        run: npm run test:prod

      - name: Get front-end coverage report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: front-end-coverage
          path: front/coverage/bobapp
        
      - name: SonarCloud scan front-end
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: -Dsonar.qualitygate.wait=true
  
  back-end-docker:
    runs-on: ubuntu-latest
    needs: back-end-check
    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build back-end Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:${{ github.sha }} .

      - name: Push back-end Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:${{ github.sha }}
      
      - name: Tag as latest
        run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:latest

      - name: Push latest tag
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-back:latest
  
  front-end-docker:
    runs-on: ubuntu-latest
    needs: front-end-check
    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build front-end Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-front:${{ github.sha }} .

      - name: Push front-end Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-front:${{ github.sha }}
      
      - name: Tag as latest
        run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-front:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-front:latest

      - name: Push latest tag
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/bobapp-front:latest